api_platform:
    mapping:
        paths:
          - '%kernel.project_dir%/config/api_platform/resources/'
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    title: Esports Videos
    version: 1.0.0
    formats:
        jsonld:   ['application/ld+json']
        json:     ['application/json']
        html:     ['text/html']
