framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    session:
        handler_id: ~
    php_errors:
        log: true
    cache: ~
    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/config/serializer/']
