lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/var/jwt/private.pem'
    public_key_path: '%kernel.project_dir%/var/jwt/public.pem'
    pass_phrase: '%env(jwt_key_pass_phrase)%'
    token_ttl:  '%env(jwt_token_ttl)%'
    user_identity_field: email
