version: '3.4'

services:
  nginx:
    build: 
      context: './docker/nginx/'
    depends_on:
      - 'php'
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - './public:/srv/esports_videos/public:ro'

  php:
    build:
      context: './docker/php-fpm'
    volumes:
      - './:/srv/esports_videos:rw,cached'
    depends_on:
      - 'mysql'
    user: 'www-data:www-data'

  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'esports_videos'
      MYSQL_USER: 'esports_videos'
      MYSQL_PASSWORD: 'esports_videos'
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'

  adminer:
    image: 'adminer'
    depends_on:
      - 'mysql'
    ports:
      - '8081:8080'

  mail:
    image: 'djfarrelly/maildev'
    ports:
      - '1025:25'
      - '1080:80'

volumes:
  db-data: {}
