version: '2'

services:
  nginx:
    image: 'nginx:1.11-alpine'
    links:
      - 'php'
    depends_on:
      - 'php'
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
      - './public:/srv/esports_videos/public:ro'

  php:
    build:
      context: './docker/php-fpm'
    volumes:
      - './:/srv/esports_videos:rw'
      - '/srv/esports_videos/var/'
      - '/srv/esports_videos/var/cache/'
      - '/srv/esports_videos/var/logs/'
      - '/srv/esports_videos/var/sessions/'
    links:
      - 'mysql'
    user: 'www-data:www-data'

  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'esports_videos'
      MYSQL_USER: 'esports_videos'
      MYSQL_PASSWORD: 'esports_videos'
    ports:
      - '3306:3306'
    volumes:
      - 'db-data:/var/lib/mysql'
  
  node:
    build:
      context: 'docker/node' 
    user: 'node:node'
    volumes:
      - './:/home/node/app'

volumes:
  db-data:
