resources:
    App\Entity\User:
        collectionOperations:
            post:
                validation_groups:
                    - 'post'
                normalization_context:
                    groups:
                        - 'get'
        itemOperations:
            get:
                normalization_context:
                    groups:
                        - 'get'
            put:
                access_control: 'object == user'
                validation_groups:
                    - 'put'
                denormalization_context:
                    groups:
                        - 'put'
                normalization_context:
                    groups:
                        - 'get'
        properties:
            id:
                identifier: false
                iri: http://schema.org/identifier
            username:
                iri: http://schema.org/additionalName
            firstName:
                iri: http://schema.org/givenName
            lastName:
                iri: http://schema.org/familyName
            email:
                iri: http://schema.org/email
            country:
                iri: http://schema.org/nationality
            slug:
                identifier: true
                iri: http://schema.org/url
