resources:
    App\Entity\User:
        collectionOperations:
            post:
                validation_groups:
                    - 'post'
                normalization_context:
                    groups:
                        - 'get'
        itemOperations:
            get:
                normalization_context:
                    groups:
                        - 'get'
            put:
                access_control: 'object == user'
                validation_groups:
                    - 'put'
                denormalization_context:
                    groups:
                        - 'put'
                normalization_context:
                    groups:
                        - 'get'
        properties:
            slug:
                identifier: true
            id:
                identifier: false
