App\Entity\User:
    attributes:
        id:
            groups: ['get']
        username:
            groups: ['get', 'put']
        plainPassword:
            groups: ['post', 'put']
        email:
            groups: ['post', 'put']
