App\Entity\User:
    attributes:
        id:
            groups: ['get']
        username:
            groups: ['get', 'post', 'put']
        plainPassword:
            groups: ['post', 'put']
        email:
            groups: ['post', 'put']
        firstName:
            groups: ['get', 'post', 'put']
        lastName:
            groups: ['get', 'post', 'put']
        country:
            groups: ['get', 'post', 'put']
