App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['email', 'username']
            groups: ['post', 'put']
    properties:
        username:
            - NotBlank: ~
        plainPassword:
            - NotBlank:
                groups: ['post']
            - Length:
                max: 4096
                min: 12
                groups: ['post']
            - Regex:
                pattern: '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*([-+_!@#$%^&*.,?])).{12,}$/'
                groups: ['post']
                message: user.validator.password.regex
        email:
            - NotBlank:
                groups: ['post']
            - Email:
                groups: ['post']
