services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

when@dev: &fixtures
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        DataFixtures\:
            resource: '../fixtures/'

when@test: *fixtures
