name: Execute CI tests

on:
    workflow_run:
        workflows: [Execute QA tests]
        types:
            - completed

jobs:
    test-smoke:
        name: Run smoke tests
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install the project for test environment
                run: make test-install

            -   name: Run smoke tests
                run: make test-smoke

    test-functional:
        name: Run functional tests
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install the project for test environment
                run: make test-install

            -   name: Run functional tests
                run: make test-functional
