name: Execute CI tests

on:
    push:
        branches:
            - main
    pull_request: ~

jobs:
    test-smoke:
        name: Run smoke tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install the project for test environment
                run: make ci-install

            -   name: Run smoke tests
                run: make test-smoke

    test-functional:
        name: Run functional tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install the project for test environment
                run: make ci-install

            -   name: Run functional tests
                run: make test-functional
